import type { ColorProfile, ColorPaletteId } from '../types/note';

export const COLOR_PROFILES: Record<ColorPaletteId, ColorProfile> = {
    canary: {
        id: 'canary',
        name: 'Canary Yellow',
        bgHex: '#FEF9C3',
        borderHex: '#EAB308',
        headerHex: '#FACC15',
        accentHex: '#CA8A04',
        textHex: '#713F12',
        badgeBg: 'bg-yellow-200 text-yellow-900 border-yellow-400',
        tailwindClass: 'bg-canary-bg text-canary-text border-canary-border',
    },
    mint: {
        id: 'mint',
        name: 'Mint Green',
        bgHex: '#DCFCE7',
        borderHex: '#22C55E',
        headerHex: '#4ADE80',
        accentHex: '#16A34A',
        textHex: '#14532D',
        badgeBg: 'bg-emerald-200 text-emerald-900 border-emerald-400',
        tailwindClass: 'bg-mint-bg text-mint-text border-mint-border',
    },
    magenta: {
        id: 'magenta',
        name: 'Magenta Rose',
        bgHex: '#FCE7F3',
        borderHex: '#E11D48',
        headerHex: '#F43F5E',
        accentHex: '#DB2777',
        textHex: '#831843',
        badgeBg: 'bg-pink-200 text-pink-900 border-pink-400',
        tailwindClass: 'bg-magenta-bg text-magenta-text border-magenta-border',
    },
    sky: {
        id: 'sky',
        name: 'Sky Blue',
        bgHex: '#E0F2FE',
        borderHex: '#0284C7',
        headerHex: '#38BDF8',
        accentHex: '#0284C7',
        textHex: '#0C4A6E',
        badgeBg: 'bg-sky-200 text-sky-900 border-sky-400',
        tailwindClass: 'bg-sky-bg text-sky-text border-sky-border',
    },
    tangerine: {
        id: 'tangerine',
        name: 'Tangerine Orange',
        bgHex: '#FFEDD5',
        borderHex: '#EA580C',
        headerHex: '#FB923C',
        accentHex: '#EA580C',
        textHex: '#7C2D12',
        badgeBg: 'bg-orange-200 text-orange-900 border-orange-400',
        tailwindClass: 'bg-tangerine-bg text-tangerine-text border-tangerine-border',
    },
    pink: {
        id: 'pink',
        name: 'Blush Pink',
        bgHex: '#FFE4E6',
        borderHex: '#EC4899',
        headerHex: '#F472B6',
        accentHex: '#E11D48',
        textHex: '#881337',
        badgeBg: 'bg-rose-200 text-rose-900 border-rose-400',
        tailwindClass: 'bg-pink-bg text-pink-text border-pink-border',
    },
};

export const COLOR_LIST = Object.values(COLOR_PROFILES);
